# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "bookinfo-operators"
version = "0.0.0"
requires-python = ">=3.11"

dependencies = [
  "jubilant",
  "pytest",
  "pytest-bdd",
  "pytest-jubilant",
]
