name: Details Charm PR

on:
  workflow_call:

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@feat/option-to-meshify-tests
    secrets: inherit
    with:
      automatically-retry-hooks: true
      charm-path: charms/bookinfo-details-k8s