name: Path Filter

on:
  workflow_call:
    outputs:
      details:
        description: "Whether bookinfo-details-k8s charm was changed"
        value: ${{ jobs.changes.outputs.details }}
      ratings:
        description: "Whether bookinfo-ratings-k8s charm was changed"
        value: ${{ jobs.changes.outputs.ratings }}
      reviews:
        description: "Whether bookinfo-reviews-k8s charm was changed"
        value: ${{ jobs.changes.outputs.reviews }}
      productpage:
        description: "Whether bookinfo-productpage-k8s charm was changed"
        value: ${{ jobs.changes.outputs.productpage }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      details: ${{ steps.changes.outputs.details }}
      ratings: ${{ steps.changes.outputs.ratings }}
      reviews: ${{ steps.changes.outputs.reviews }}
      productpage: ${{ steps.changes.outputs.productpage }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            details:
              - 'charms/bookinfo-details-k8s/**'
              - 'charms/bookinfo-libs-k8s/lib/charms/bookinfo_lib/**'
            ratings:
              - 'charms/bookinfo-ratings-k8s/**'
              - 'charms/bookinfo-libs-k8s/lib/charms/bookinfo_lib/**'
            reviews:
              - 'charms/bookinfo-reviews-k8s/**'
              - 'charms/bookinfo-libs-k8s/lib/charms/bookinfo_lib/**'
            productpage:
              - 'charms/bookinfo-productpage-k8s/**'
              - 'charms/bookinfo-libs-k8s/lib/charms/bookinfo_lib/**'